config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  devise_for :users
  resources :items

  # 単数リソースのルーティング。まりは「idがいるかいらないか」。pathにidが含まれなくなる。
  resource :user, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  # itemは1人のユーザーに所属する
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # ユーザーはたくさんのitemを持っている
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #before_action :authenticate_user!, except: :index
  before_action :move_to_index, except: :index


  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    #Item.create!(name: item_params[:name], price: item_params[:price], user_id: current_user.id)
    current_user.items.create!(item_params)
  end

  def move_to_index
    redirct_to action: :index unless user_signed_in?
  end

  private

  def item_params
    params.require(:item).permit(:name, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    #@items = Item.where(user_id: current_user.id)

    # アソシエーション設定による改善コード ~ /views/users/show.html.erb を参照 ~
    @items = current_user.items
    #@user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>投稿が完了しました</h1>
<%= link_to "投稿一覧へ戻る", items_path %>

app/views/items/index.html.erb
<<h1>購入商品一覧</h1>
<% if user_signed_in? %>
  <table>
    <thead>
      <tr>
        <th>商品名</th>
        <th>値段</th>
        <th>購入者</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td>¥<%= item.price %></td>
          <td><%= item.user.nickname.present? ? "#{item.user.nickname}" : "会員No. #{item.user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <P>ログインしてください</P>
<% end %>

app/views/items/new.html.erb
<h1>ご購入商品の情報を入力</h1>
<%= form_with model: @item, local: true do |f| %>
  <p><%= f.label :name, "商品名" %> <%= f.text_field :name %></p>
  <p><%= f.label :price, "値段" %> <%= f.text_field :price %></p>
  <%= f.submit "送信" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <!-- ログイン時 -->
      <%= link_to "トップ", items_path %>
      <%= link_to "投稿画面へ", new_item_path%>
      <%= link_to "マイページへ", user_path %>
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか?" } %>
    <% else %>
      <!-- 非ログイン時 -->
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "アカウント登録", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<p><%= current_user.nickname.present? ? "#{current_user.nickname}" : "#{current_user.email}" %>さん</p>
<h1>購入商品一覧</h1>
<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>値段</th>
    </tr>
  </thead>
  <tbody>
    <%# @user.items.each do |item| %> <!-- users_controllerのshowを参照 -->
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td>¥<%= item.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>